// Rehydration store
export const REHYDRATION_SET_REHYDRATION_VALUE =
    'REHYDRATION_SET_REHYDRATION_VALUE';

// CONTAINER ACTIONS
export const CONTAINER_SET_CONTROLS = 'CONTAINER_SET_CONTROLS';
export const CONTAINER_SET_CURRENT_SCREEN_NAME =
    'CONTAINER_SET_CURRENT_SCREEN_NAME';
